# -*- coding: utf-8 -*-
"""МО_Барабаш_ЛР№8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MaXrWHGa7au_3L1VTSuab6EXPtfked7P
"""

# Очистка и установка
!pkill -f streamlit 2>/dev/null
!lsof -ti:8501 | xargs kill -9 2>/dev/null
!rm -rf /root/.cache/streamlit
!pip install --upgrade streamlit plotly pandas numpy matplotlib seaborn scikit-learn

print("✅ Готово!")

# Установка ngrok
!pip install pyngrok

# Регистрация на ngrok (бесплатно, 1 минута)
print("="*60)
print("🔑 НУЖНА БЫСТРАЯ РЕГИСТРАЦИЯ В NGROK")
print("="*60)
print("""
1. Перейдите на https://dashboard.ngrok.com/signup
2. Зарегистрируйтесь (через Google/GitHub или email)
3. Получите ваш authtoken (в личном кабинете)
4. Скопируйте токен и вставьте его ниже
""")

# Вставьте ваш токен сюда
AUTH_TOKEN = input("Вставьте ваш ngrok authtoken: ")

# Настройка ngrok
!ngrok config add-authtoken {AUTH_TOKEN}
print("✅ ngrok настроен!")

"""Создание Streamlit-приложения (файл app.py)"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import numpy as np
# import matplotlib.pyplot as plt
# import seaborn as sns
# import plotly.express as px
# import plotly.graph_objects as go
# from sklearn.model_selection import train_test_split, cross_val_score
# from sklearn.preprocessing import LabelEncoder, StandardScaler
# from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
# from sklearn.linear_model import LinearRegression, Ridge, Lasso
# from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
# import warnings
# warnings.filterwarnings('ignore')
# 
# # Настройка страницы
# st.set_page_config(
#     page_title="Анализ продаж смартфонов",
#     page_icon="📱",
#     layout="wide"
# )
# 
# # Заголовок
# st.title("📱 Анализ и прогнозирование продаж смартфонов")
# st.markdown("---")
# 
# # Загрузка данных
# @st.cache_data
# def load_data():
#     df = pd.read_csv('Datacat.csv')
#     return df
# 
# try:
#     df = load_data()
#     st.success(f"✅ Данные загружены: {df.shape[0]} записей, {df.shape[1]} признаков")
# except Exception as e:
#     st.error(f"Ошибка загрузки: {e}")
#     st.stop()
# 
# # Боковая панель
# st.sidebar.header("⚙️ Настройки")
# 
# # Выбор модели
# model_name = st.sidebar.selectbox(
#     "🤖 Выберите модель",
#     ["Linear Regression", "Ridge Regression", "Lasso Regression", "Random Forest", "Gradient Boosting"]
# )
# 
# # Гиперпараметры
# if model_name == "Random Forest":
#     n_estimators = st.sidebar.slider("Количество деревьев", 10, 200, 100)
#     max_depth = st.sidebar.slider("Максимальная глубина", 1, 20, 10)
# elif model_name == "Gradient Boosting":
#     n_estimators = st.sidebar.slider("Количество деревьев", 10, 200, 100)
#     learning_rate = st.sidebar.slider("Скорость обучения", 0.01, 0.3, 0.1)
# elif model_name == "Ridge Regression":
#     alpha = st.sidebar.slider("Alpha", 0.01, 10.0, 1.0)
# elif model_name == "Lasso Regression":
#     alpha = st.sidebar.slider("Alpha", 0.01, 10.0, 1.0)
# 
# # Параметры разделения
# test_size = st.sidebar.slider("Размер тестовой выборки", 0.1, 0.4, 0.2, 0.05)
# target_col = st.sidebar.selectbox("Целевая переменная", ["Revenue_USD", "Units_Sold", "Price_USD"])
# 
# # Кнопка обучения
# train_clicked = st.sidebar.button("🚀 Обучить модель", type="primary", use_container_width=True)
# 
# # Создание вкладок
# tab1, tab2, tab3, tab4 = st.tabs(["📊 Данные", "📈 Визуализация", "🤖 Обучение", "📉 Результаты"])
# 
# # TAB 1: ДАННЫЕ
# with tab1:
#     st.header("Обзор данных")
# 
#     col1, col2, col3, col4 = st.columns(4)
#     col1.metric("Всего записей", df.shape[0])
#     col2.metric("Всего признаков", df.shape[1])
#     col3.metric("Количество брендов", df['Brand'].nunique())
#     col4.metric("Средняя выручка", f"${df['Revenue_USD'].mean():,.0f}")
# 
#     st.subheader("Первые 15 строк")
#     st.dataframe(df.head(15), use_container_width=True)
# 
#     st.subheader("Статистика числовых признаков")
#     st.dataframe(df.describe(), use_container_width=True)
# 
#     st.subheader("Информация о пропусках")
#     missing = df.isnull().sum()
#     if missing.sum() == 0:
#         st.success("✅ Пропусков в данных нет")
#     else:
#         st.warning(f"⚠️ Найдено пропусков: {missing.sum()}")
# 
# # TAB 2: ВИЗУАЛИЗАЦИЯ
# with tab2:
#     st.header("Визуализация данных")
# 
#     # Выбор графика
#     chart_type = st.selectbox(
#         "Выберите тип графика",
#         ["Выручка по брендам", "Выручка по странам", "Цена vs Выручка", "Распределение цен", "Корреляционная матрица"]
#     )
# 
#     if chart_type == "Выручка по брендам":
#         brand_sales = df.groupby('Brand')['Revenue_USD'].sum().sort_values()
#         fig = px.bar(
#             x=brand_sales.values, y=brand_sales.index, orientation='h',
#             title='Общая выручка по брендам',
#             labels={'x': 'Выручка (USD)', 'y': 'Бренд'},
#             color=brand_sales.values, color_continuous_scale='Viridis'
#         )
#         st.plotly_chart(fig, use_container_width=True)
# 
#     elif chart_type == "Выручка по странам":
#         country_sales = df.groupby('Country')['Revenue_USD'].sum().sort_values(ascending=False).head(10)
#         fig = px.bar(
#             x=country_sales.index, y=country_sales.values,
#             title='Топ-10 стран по выручке',
#             labels={'x': 'Страна', 'y': 'Выручка (USD)'},
#             color=country_sales.values, color_continuous_scale='Plasma'
#         )
#         st.plotly_chart(fig, use_container_width=True)
# 
#     elif chart_type == "Цена vs Выручка":
#         fig = px.scatter(
#             df, x='Price_USD', y='Revenue_USD', color='Brand', size='Units_Sold',
#             title='Зависимость цены от выручки',
#             labels={'Price_USD': 'Цена (USD)', 'Revenue_USD': 'Выручка (USD)'},
#             hover_data=['Model', 'Country']
#         )
#         st.plotly_chart(fig, use_container_width=True)
# 
#     elif chart_type == "Распределение цен":
#         fig = px.histogram(
#             df, x='Price_USD', nbins=30, title='Распределение цен смартфонов',
#             labels={'Price_USD': 'Цена (USD)'},
#             color_discrete_sequence=['#3498db']
#         )
#         st.plotly_chart(fig, use_container_width=True)
# 
#     elif chart_type == "Корреляционная матрица":
#         numeric_cols = df.select_dtypes(include=[np.number]).columns
#         corr = df[numeric_cols].corr()
#         fig = px.imshow(
#             corr, text_auto=True, aspect='auto',
#             title='Корреляция между признаками',
#             color_continuous_scale='RdBu'
#         )
#         st.plotly_chart(fig, use_container_width=True)
# 
# # TAB 3: ОБУЧЕНИЕ
# with tab3:
#     st.header("Обучение модели")
# 
#     if train_clicked:
#         with st.spinner("Подготовка данных..."):
#             # Кодирование категориальных признаков
#             categorical_cols = ['Brand', 'Country', 'Storage', 'Color', 'Payment_Method']
#             df_encoded = df.copy()
# 
#             for col in categorical_cols:
#                 le = LabelEncoder()
#                 df_encoded[col] = le.fit_transform(df_encoded[col])
# 
#             # Подготовка признаков
#             exclude_cols = ['Sale_ID', 'Model', target_col]
#             feature_cols = [c for c in df_encoded.columns if c not in exclude_cols]
#             X = df_encoded[feature_cols]
#             y = df_encoded[target_col]
# 
#             # Разделение
#             X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=test_size, random_state=42)
# 
#             # Масштабирование
#             scaler = StandardScaler()
#             X_train_scaled = scaler.fit_transform(X_train)
#             X_test_scaled = scaler.transform(X_test)
# 
#             st.write(f"**Обучающая выборка:** {len(X_train)} записей")
#             st.write(f"**Тестовая выборка:** {len(X_test)} записей")
#             st.write(f"**Количество признаков:** {len(feature_cols)}")
# 
#         with st.spinner(f"Обучение модели {model_name}..."):
#             # Создание модели
#             if model_name == "Linear Regression":
#                 model = LinearRegression()
#             elif model_name == "Ridge Regression":
#                 model = Ridge(alpha=alpha)
#             elif model_name == "Lasso Regression":
#                 model = Lasso(alpha=alpha)
#             elif model_name == "Random Forest":
#                 model = RandomForestRegressor(n_estimators=n_estimators, max_depth=max_depth, random_state=42)
#             elif model_name == "Gradient Boosting":
#                 model = GradientBoostingRegressor(n_estimators=n_estimators, learning_rate=learning_rate, random_state=42)
# 
#             # Обучение
#             model.fit(X_train_scaled, y_train)
#             y_pred = model.predict(X_test_scaled)
# 
#             # Сохраняем в session state
#             st.session_state['trained'] = True
#             st.session_state['y_test'] = y_test
#             st.session_state['y_pred'] = y_pred
#             st.session_state['model_name'] = model_name
#             st.session_state['target'] = target_col
# 
#             # Метрики
#             mae = mean_absolute_error(y_test, y_pred)
#             mse = mean_squared_error(y_test, y_pred)
#             rmse = np.sqrt(mse)
#             r2 = r2_score(y_test, y_pred)
# 
#             st.session_state['mae'] = mae
#             st.session_state['rmse'] = rmse
#             st.session_state['r2'] = r2
# 
#         st.success(f"✅ Модель {model_name} успешно обучена!")
# 
#         # Показываем метрики
#         col1, col2, col3, col4 = st.columns(4)
#         col1.metric("MAE", f"{mae:,.2f}")
#         col2.metric("MSE", f"{mse:,.2f}")
#         col3.metric("RMSE", f"{rmse:,.2f}")
#         col4.metric("R²", f"{r2:.4f}")
# 
#         # Кросс-валидация
#         with st.spinner("Выполняется кросс-валидация..."):
#             cv_scores = cross_val_score(model, X_train_scaled, y_train, cv=5, scoring='r2')
#             st.write(f"**R² на кросс-валидации (5-fold):** {cv_scores.mean():.4f} (±{cv_scores.std():.4f})")
# 
#         # Важность признаков
#         if hasattr(model, 'feature_importances_'):
#             st.subheader("Важность признаков")
#             importance_df = pd.DataFrame({
#                 'Признак': feature_cols,
#                 'Важность': model.feature_importances_
#             }).sort_values('Важность', ascending=False)
# 
#             fig, ax = plt.subplots(figsize=(10, 6))
#             ax.barh(importance_df['Признак'][:10], importance_df['Важность'][:10], color='#2ecc71')
#             ax.set_xlabel('Важность')
#             ax.set_title('Топ-10 важных признаков')
#             ax.invert_yaxis()
#             st.pyplot(fig)
# 
#     else:
#         st.info("ℹ️ Нажмите кнопку 'Обучить модель' в боковой панели")
# 
# # TAB 4: РЕЗУЛЬТАТЫ
# with tab4:
#     st.header("Результаты прогнозирования")
# 
#     if 'trained' in st.session_state and st.session_state['trained']:
#         y_test = st.session_state['y_test']
#         y_pred = st.session_state['y_pred']
# 
#         # График: Реальные vs Предсказанные
#         st.subheader("Сравнение реальных и предсказанных значений")
#         fig, ax = plt.subplots(figsize=(10, 5))
#         ax.scatter(y_test, y_pred, alpha=0.5, c='#3498db', edgecolors='white', s=60)
#         ax.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--', lw=2)
#         ax.set_xlabel(f'Реальные значения ({st.session_state["target"]})')
#         ax.set_ylabel(f'Предсказанные значения ({st.session_state["target"]})')
#         ax.set_title(f'{st.session_state["model_name"]}: Реальные vs Предсказанные (R² = {st.session_state["r2"]:.4f})')
#         ax.grid(True, alpha=0.3)
#         st.pyplot(fig)
# 
#         # График: Ошибки
#         st.subheader("Распределение ошибок")
#         errors = y_test - y_pred
#         fig2, ax2 = plt.subplots(figsize=(10, 5))
#         ax2.hist(errors, bins=30, edgecolor='black', alpha=0.7, color='#e74c3c')
#         ax2.axvline(x=0, color='blue', linestyle='--', lw=2)
#         ax2.axvline(x=np.mean(errors), color='green', linestyle='--', lw=2, label=f'Среднее: {np.mean(errors):.2f}')
#         ax2.set_xlabel('Ошибка')
#         ax2.set_ylabel('Частота')
#         ax2.set_title('Распределение ошибок прогноза')
#         ax2.legend()
#         ax2.grid(True, alpha=0.3)
#         st.pyplot(fig2)
# 
#         # Выводы
#         st.subheader("Выводы")
#         if st.session_state['r2'] > 0.8:
#             st.success(f"✅ **Отличный результат!** Модель объясняет {st.session_state['r2']*100:.1f}% дисперсии данных.")
#         elif st.session_state['r2'] > 0.6:
#             st.info(f"📈 **Хороший результат.** Модель объясняет {st.session_state['r2']*100:.1f}% дисперсии данных.")
#         elif st.session_state['r2'] > 0.4:
#             st.warning(f"⚠️ **Удовлетворительный результат.** Модель объясняет {st.session_state['r2']*100:.1f}% дисперсии данных.")
#         else:
#             st.error(f"❌ **Низкое качество.** Модель объясняет только {st.session_state['r2']*100:.1f}% дисперсии.")
# 
#         st.write(f"**Средняя абсолютная ошибка (MAE):** {st.session_state['mae']:.2f}")
#         st.write(f"Это означает, что в среднем модель ошибается на ${st.session_state['mae']:.0f} при прогнозировании {st.session_state['target']}")
# 
#     else:
#         st.info("ℹ️ Сначала обучите модель во вкладке 'Обучение'")
# 
# # Footer
# st.markdown("---")
# st.markdown(
#     "<div style='text-align: center; color: gray;'>Лабораторная работа: Веб-приложение для демонстрации моделей ML</div>",
#     unsafe_allow_html=True
# )

"""Запуск приложения через ngrok"""

from pyngrok import ngrok
import subprocess
import time
import threading

# Останавливаем всё
subprocess.run(["pkill", "-f", "streamlit"], shell=True)
time.sleep(2)

# Запускаем Streamlit в фоне
print("🚀 Запуск Streamlit...")
subprocess.Popen(
    "streamlit run app.py --server.port=8501 --server.headless=true",
    shell=True,
    stdout=subprocess.DEVNULL,
    stderr=subprocess.DEVNULL
)

time.sleep(8)

# Создаём туннель ngrok
print("🔗 Создание публичного туннеля...")
try:
    # Закрываем старый туннель если есть
    ngrok.kill()

    # Создаём новый
    tunnel = ngrok.connect(8501)
    public_url = tunnel.public_url

    print("\n" + "="*60)
    print("✅ ПРИЛОЖЕНИЕ ЗАПУЩЕНО!")
    print("="*60)
    print(f"\n🌐 ВАША РАБОЧАЯ ССЫЛКА:")
    print(f"   {public_url}")
    print("\n📌 ИНСТРУКЦИЯ:")
    print("   1. Нажмите на ссылку выше")
    print("   2. Приложение откроется в браузере")
    print("   3. Ссылка активна, пока работает Colab")
    print("\n" + "="*60)

except Exception as e:
    print(f"Ошибка: {e}")
    print("\n⚠️ Если не работает, выполните ячейку 1 сначала и введите правильный токен")